version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"

  honeypot:
    build: ./honeypot
    ports:
      - "4001:4001"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - honeypot
