worker_processes 1;

events { worker_connections 1024; }

http {
    lua_shared_dict ip_counters 10m;

    log_format tracked_ips '$remote_addr [$time_local]';

    resolver 127.0.0.11;

    server {
        listen 80;

        location /login {
            set $is_malicious "";

            access_by_lua_block {
                local limit = 60
                local ip = ngx.var.remote_addr
                local dict = ngx.shared.ip_counters
                
                local reqs, err = dict:incr(ip, 1, 0, 60)
                
                if reqs and reqs > limit then
                    ngx.var.is_malicious = "1"
                    return ngx.redirect("http://localhost:4001/login")
                end
            }

            access_log /var/log/nginx/honeypot/blocked_ips.log tracked_ips if=$is_malicious;

            proxy_pass http://backend:4000;
        }
    }
}
